version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"
    environment:
      # OPAM seems to be quite unhappy without $TERM and Circle doesn't seem to set one.
      TERM: vt100
      MACOSX_DEPLOYMENT_TARGET: "10.11"
      OPAM_REPO: repo/darwin
      OPAM_COMP: 4.03.0
      OPAMVERBOSE: 1
      OPAMYES: 1
    steps:
      - checkout
      - run:
          name: Configure environment
          command: |
            echo 'export GOPATH=${HOME}/go' >> $BASH_ENV
            echo 'export PROJECT_ROOT=${GOPATH}/src/github.com/moby/hyperkit' >> $BASH_ENV
            echo 'export PATH=${PATH}:${GOPATH}/bin' >> $BASH_ENV
      - run: env
      - run: make clean
      - run: make all
      - run: test ! -s build/lib/mirage_block_ocaml.cmi || (echo "qcow libraries have been pre-installed in CI environment" && exit 1)
      - run: make test
      # brew has moved the python bottle from python2 to python3. The
      # circleci base image currently predates this (so python==python
      # 2.7.3). opam depends (somewhere in the dependency tree) on
      # python@2 which is the explicit Python 2 but brew seems not to
      # be able to properly sequence the upgrade of python from 2 to 3
      # while also installing the explicit python@2 which results in
      # file conflicts:
      #
      #     ==> Pouring python@2-2.7.14_3.sierra.bottle.1.tar.gz
      #     Error: The `brew link` step did not complete successfully
      #     The formula built, but is not symlinked into /usr/local
      #     Could not symlink bin/2to3-2
      #     Target /usr/local/bin/2to3-2
      #     is a symlink belonging to python. You can unlink it:
      #
      # Manually upgrading the python bottle allows us to avoid this
      # until the base image is updated.
      - run: brew upgrade python
      # Install opam 1 until we become opam 2 compatible
      - run: brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/72ce8812eaa33abe23533dfa021b51351a6b9c3e/Formula/opam.rb
      - run: opam init -v -n --comp="${OPAM_COMP}" --switch="${OPAM_COMP}" local "${OPAM_REPO}"
      - run: opam config exec -- opam depext -i hyperkit
      - run: opam config exec -- make clean
      - run: opam config exec -- make all
      - run: opam config exec -- make test
      - run: opam config exec -- make test-qcow
      # Go related steps
      - run: mkdir -p $(dirname "$PROJECT_ROOT")
      - run: ln -s $(pwd) "$PROJECT_ROOT"
      - run: brew install golang
      - run: (cd go; make ci)
      - run: make artifacts
      - store_artifacts:
          path: build/hyperkit
          destination: hyperkit
      - store_artifacts:
          path: build/hyperkit.sym
          destination: hyperkit.sym
      - store_artifacts:
          path: build/COMMIT
          destination: COMMIT
      - store_artifacts:
          path: build/LICENSE
          destination: LICENSE
      - store_artifacts:
          path: test/disk.dmg
          destination: test/disk.dmg
      - store_artifacts:
          path: test/disk.qcow2
          destination: test/disk.qcow2
